/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.tsunami.callbackserver.server.common.monitoring;

import io.netty.handler.codec.dns.DnsResponseCode;
import io.netty.handler.codec.http.HttpResponseStatus;
import java.time.Duration;
import java.util.Optional;

/** Observes important events generated by TCS for monitoring purposes. */
public interface TcsEventsObserver {
  void onSuccessfulHttpRpc(
      String endpointName, Duration responseTime, HttpResponseStatus responseCode);

  void onFailedHttpRpc(
      String endpointName,
      Duration responseTime,
      HttpResponseStatus responseCode,
      Optional<Exception> ex);

  default void onFailedHttpRpc(
      String endpointName, Duration responseTime, HttpResponseStatus responseCode, Exception ex) {
    onFailedHttpRpc(endpointName, responseTime, responseCode, Optional.of(ex));
  }

  default void onFailedHttpRpc(
      String endpointName, Duration responseTime, HttpResponseStatus responseCode) {
    onFailedHttpRpc(endpointName, responseTime, responseCode, Optional.empty());
  }

  void onSuccessfulDnsRpc(String endpointName, Duration responseTime);

  void onFailedDnsRpc(
      String endpointName,
      Duration responseTime,
      DnsResponseCode responseCode,
      Optional<Exception> ex);

  default void onFailedDnsRpc(
      String endpointName, Duration responseTime, DnsResponseCode responseCode, Exception ex) {
    onFailedDnsRpc(endpointName, responseTime, responseCode, Optional.of(ex));
  }

  default void onFailedDnsRpc(
      String endpointName, Duration responseTime, DnsResponseCode responseCode) {
    onFailedDnsRpc(endpointName, responseTime, responseCode, Optional.empty());
  }

  void onHttpInteractionRecorded();

  void onDnsInteractionRecorded();

  void onHttpInteractionFound();

  void onDnsInteractionFound();

  void onInteractionNotFound();

  default void init() {}
}
